# Generated by Django 5.2.1 on 2025-05-22 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('town', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_establishment', models.DateField(blank=True, null=True)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_images/')),
                ('isbn', models.CharField(blank=True, max_length=100, null=True)),
                ('year_release', models.DateField(blank=True, null=True)),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('book_dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('publisher_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_shop.publisherhouse')),
            ],
        ),
    ]
