# Generated by Django 5.2.1 on 2025-05-23 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category_book',
            field=models.CharField(blank=True, choices=[('R', 'Romance'), ('T', 'Thriller'), ('B', 'Biography'), ('C', 'Classic'), ('D', 'Drama'), ('H', 'History')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='type_book',
            field=models.CharField(blank=True, choices=[('S', 'Soft'), ('H', 'Hard')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='publisherhouse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
