# Generated by Django 5.2.1 on 2025-05-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='bakers',
            new_name='baker',
        ),
    ]
