# Generated by Django 5.2.1 on 2025-05-19 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_shop', '0002_rename_bakers_cake_baker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='baker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='cake_shop.baker'),
        ),
    ]
